services:
  app:
    build: .
    container_name: lighthouse_app
    depends_on:
      - mongodb
    environment:
      - CONNECTION_STRING=mongodb://localhost:27017
      - DB_NAME=lighthouseDB
      - LIGHTHOUSE_PATH=/usr/bin/lighthouse
    ports:
      - "8080:8080"
    volumes:
      - ./korea_public_website_url_2.json:/app/korea_public_website_url_2.json
    command: ["sh", "-c", "sleep 5 && java -jar app.jar"]

  mongodb:
    image: mongo:7
    container_name: lighthouse_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: